### ISSUE TITLE
Is x-pack built-in with this version?

### ISSUE THREAD

**Issue by NassiHarel** [pires/kubernetes-elasticsearch-cluster#109]
if it is, how do I make it work?

like this? in which yml? what is the url?
- name: "ES_PLUGINS_INSTALL"
  value: "x-pack"

(too many questions...)
Thanks

**Comment by pires** [comment]
> Is x-pack built-in with this version

If it is, then you don't need to install it as a plug-in, right?

> like this? in which yml? what is the url?

I have no clue what this means. You should learn a little bit more about Elasticsearch and how to install plug-ins. Then you should learn about Kubernetes pods and how to set environment variables. Only then will you understand where to set the environment variable as [clearly described in the documentation](https://github.com/pires/kubernetes-elasticsearch-cluster#plugins).

**Comment by NassiHarel** [comment]
Thank you for the reply.
I am working with ES for 2 years and with Kubernetes 1.5 years

the  environment variables should be at?
es-client.yaml  OR
es-data.yaml  OR
es-master.yaml

**Comment by NassiHarel** [comment]
I will see inside the docker if the plugin exists.
The env should be in all ES nodes...

**Comment by pires** [comment]
I've never used this plug-in in particular but I'd say all nodes. You should confirm the plug-in docs.

**Comment by mohankrishnavanga** [comment]
Hi, 
I am not able to install x-pack by providing the environment variable as it needs a confirmation from user (by default it is taking no) with kubernetes. Can you help with this? 

I modified the dockerfile like this: 

FROM quay.io/pires/docker-elasticsearch:6.1.0

MAINTAINER krish

USER root

# Override config, otherwise plug-in install will fail
ADD config /elasticsearch/config

# Set environment
ENV DISCOVERY_SERVICE elasticsearch-discovery
ENV NODE_NAME sample-node
ENV ES_PLUGINS_INSTALL x-pack

#Install x-pack
#RUN  elasticsearch-plugin install --batch "x-pack"

# Kubernetes requires swap is turned off, so memory lock is redundant
ENV MEMORY_LOCK false

and  I get the following error:


[2017-12-18T16:35:10,445][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-master1-540331866-2q8b1] uncaught exception in thread [main]
--
  | org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
  | at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.0.jar:6.1.0]
  | at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.0.jar:6.1.0]
  | Caused by: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
  | at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.0.jar:6.1.0]
  | ... 6 more
  | Caused by: java.io.IOException: Cannot run program "/elasticsearch/plugins/x-pack/platform/linux-x86_64/bin/controller": error=2, No such file or directory
  | at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_151]
  | at org.elasticsearch.bootstrap.Spawner.spawnNativePluginController(Spawner.java:129) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:93) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.0.jar:6.1.0]
  | ... 6 more
  | Caused by: java.io.IOException: error=2, No such file or directory
  | at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_151]
  | at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[?:1.8.0_151]
  | at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_151]
  | at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_151]
  | at org.elasticsearch.bootstrap.Spawner.spawnNativePluginController(Spawner.java:129) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:93) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.0.jar:6.1.0]
  | at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.0.jar:6.1.0]
  | ... 6 more

Not able to over-ride the prompt and the files are not getting downloaded.

**Comment by pires** [comment]
You should be fine if you use (your own) image that has this one as base image.

**Comment by mohankrishnavanga** [comment]
I did try it out in my local environment but I'm having the issue I
mentioned.
