### ISSUE TITLE
repository-gcs authentication

### ISSUE THREAD

**Issue by webattitude** [pires/kubernetes-elasticsearch-cluster#126]
Hi, I've installed repository-gcs plugin, but I don't know how to set authentication mechanism.
TIA,
Thomas

**Comment by tutoring** [comment]
Thomas, I am trying to use this plugin and I believe, that authentication is best achieved by allowing your cluster to access the default credentials on GCS. That is to say, if you are using Container/Compute Engine (which I'll assume), then you can simply allow access to your buckets by giving permission when you create the cluster (or instances). See here: https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-gcs-usage.html

However, after setting things up as mentioned above on GCS, I am having problems with this plugin because I'm getting the error: 
> repository type [gcs] does not exist
I've opened a new issue for that here: #159

**Comment by pires** [comment]
We're installing the plug-ins before Elasticsearch starts so there's no need for restarting Elasticsearch.

Please, follow the [official instructions](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-gcs-usage.html) for the respective plug-in. If it doesn't work, you should reach to the Elasticsearch project.
