### ISSUE TITLE
kibana container takes forever to start ("Optimizing...")

### ISSUE THREAD

**Issue by Morriz** [pires/kubernetes-elasticsearch-cluster#147]
The logs just show nothing beyond:

```
Optimizing and caching bundles for kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes
```

And I have been waiting for 25 minutes...

**Comment by sagikazarmark** [comment]
See this discussion: https://github.com/elastic/kibana-docker/issues/27

**Comment by gilblau** [comment]
@sagikazarmark - I am confused (after going over the discussion) is the issue resolved?

I am planning to run ELK on K8s and in production environment, and I need to know it will "work with no major issues".

Thanks!

**Comment by sagikazarmark** [comment]
You can find a solution for this particular problem in the linked ticket.

As for running ELK on k8s: not an easy thing to do, because of the statefulness not necessarily recommended, but for things like logging it can be ok.

It takes some time to find the optimal setup, it doesn't work like next, next, finish.

**Comment by pires** [comment]
Thank you @sagikazarmark!

**Comment by Zhan-Jie** [comment]
why is  boot process of kibana so slow on docker ?? It takes about half an hour to optimize what stupid things..
