### ISSUE TITLE
[Help request] Kibana official images

### ISSUE THREAD

**Issue by Unb0rn** [pires/kubernetes-elasticsearch-cluster#163]
Hello! I am trying to make this all work with original docker images from elastic docker repo.
It was not so hard to make elastic up and running, because pires left all the dockerfiles and configs for his customised images here oh GitHub.
But kibana deployment uses some kind of customised images with dockerfiles nowhere to be found. 
So, the question is-how does the Kibana know where to connect?
There is no such variable in yaml, so I assume, some kind of discovery should be in the image.
Thanks!

**Comment by selangley** [comment]
I modified my kibana.yaml to use:

  image: docker.elastic.co/kibana/kibana-oss:6.1.1

where kibana-oss is the version of Kibana that Elastic has made available without X-Pack included.

Then you need to remove the name value pairs that disable the X-Pack features from your kibana.yml because those plugins are no longer there.

**Comment by pires** [comment]
Feel free to open a PR that updates the Kibana part.

**Comment by kskewes** [comment]
@Unb0rn 
Pires has recently accepted my pull request to update to Kibana OSS image. 
Kibana connects to Elastic Search through standard (ES standard) ports. 

Try pull the latest and see how you get on. 

Just note that for the kibana service exposes kibana on port 80. In my own setup I kept everything on standard ES ports (ie: kibana 5601) and ran a nginx proxy in front.
