### ISSUE TITLE
Abusing image tags?

### ISSUE THREAD

**Issue by jasonkuhrt** [pires/kubernetes-elasticsearch-cluster#3]
I noticed you are using tags to differentiate the parts of the Elasticsearch images (data, master, API).

Would it not be better to reserve the tags for the `semver` version info? Right now I don't have a choice as to which version of Elasticsearch I want to use.

**Comment by pires** [comment]
That's something I gave a thought about and the thing is that for me to provide automated trusted builds, all three Dockerfiles needed to share the same repo. Otherwise, you won't be able to use ```pires/elasticsearch``` for all of them. And actually, in order to tag images and pull them, I'll have to do it by hand. So, instead of ```elasticsearch:lb-latest``` you can have ```elasticsearch:lb-1.4.1``` or similar. How would that work out for you?

**Comment by jasonkuhrt** [comment]
Yeah that probably makes the most sense. Sigh, I feel like Docker has a half-baked abstraction around tags and distribution. At least `git` allows multiple tags per node. : (

**Comment by pires** [comment]
@jasonkuhrt I feel your pain.
