### ISSUE TITLE
Status "yellow"

### ISSUE THREAD

**Issue by codingwithoutcomments** [pires/kubernetes-elasticsearch-cluster#33]
When I scale up to 2 client and 3 master pods then do a curl on the cluster I get status "yellow"

curl http://ip_address:9200/_cluster/health?pretty
{
  "cluster_name" : "myesdb",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 6,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 5,
  "active_shards" : 5,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 5,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}

Any idea what is going wrong?

Thanks

**Comment by codingwithoutcomments** [comment]
Could this also be why my data isn't persistent even though I use a persistent disk for my data cluster?

**Comment by codingwithoutcomments** [comment]
OK.  I scaled up my data nodes to "2" each having a different persistent disk.  My data nodes have persistent disks, but my client and master nodes do not.  If all the nodes are killed, but my disks aren't, will I still lose all my indexes on reboot?

**Comment by pires** [comment]
> "unassigned_shards" : 5,

This is why it's yellow. Not sure about the configuration, but you need to make sure you provide enough nodes to satisfy your sharding needs.

> If all the nodes are killed, but my disks aren't, will I still lose all my indexes on reboot?

If new data nodes are provisioned with said disks, and since it's just Lucene stuff, it should be OK.

One note I want to make sure you're following:
> Attention: As of the moment, Kubernetes pod descriptors use an emptyDir for storing data in each data node container. This is meant to be for the sake of simplicity and should be adapted according to your storage needs.

Use this repo as an enabler to your Elasticsearch cluster on top of Kubernetes but do not assume this is ready for production. One will always need to set-up the Elasticserch configuration and persistent volumes per the desired scenario. I tried to be as agnostic as possible for the sake of simplicity.
