### ISSUE TITLE
How can I spin up multiple, independent elasticsearch instances on the same kubernetes cluster?

### ISSUE THREAD

**Issue by TimHeckel** [pires/kubernetes-elasticsearch-cluster#7]
This is probably simple, but I've spun up the 5-node based kubernetes cluster by following the [AWS tutorial](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws.md), and was able to follow your instructions to create the elasticsearch service on the cluster.

So all of that is wonderful, but here's my question: *can I create multiple elasticsearch instances (a set of master, data, and load balancers) that are independent of one another on the same cluster*?

I'd like to have multiple, independent elasticsearch clusters running on the same 5-node (or whatever physical count) AWS kubernetes cluster. I have many different organizations and would like each to have a dedicated elasticsearch instance, and want all of it to run on the same kubernetes cluster. I'm sure this is feasible, but I'm curious if just re-running the kubectl create commands would suffice?

Hope that makes sense! Thank you so much for your help.

**Comment by pires** [comment]
Makes perfect sense! I'll have to change Docker files so that's possible to pass Elasticsearch configuration file to the container.

**Comment by pires** [comment]
@TimHeckel I've been thinking about this and here's some thoughts:

* Right now, you'd have to change `elasticsearch.yaml` and generate a Docker image per Elasticsearch cluster and node type (maximum of three, one master, one load-balancer, one data-node)
* This is not optimal, but AFAIK there's no way of reusing `elasticsearch.yml` and just overwrite the cluster name so it may be the only chance for you to do it
* Another idea I had was to make it possible to pass Elasticsearch a configuration folder (where `elasticsearch.yml` and other configuration files would reside), but this way you'd have to provide the files in each host that would be running the pods

This brought me to an halt. But since I have https://github.com/pires/docker-elasticsearch, I'm thinking about adding a script that will read environment variables passed to Docker, like `ES_CLUSTER_NAME`, replace in `elasticsearch.yml`and start Elasticsearch. What do you think?

**Comment by tamsky** [comment]
Environment variables >> static config files

+1 to using environment variables (some required, such as `ES_CLUSTER_NAME`, and sane defaults for others) to populate the `elasticsearch.yml` file on initial startup.

**Comment by andrewmclagan** [comment]
I'd use kubernetes namespaces...
