### ISSUE TITLE
StatefulSet Data node: PVC and PV matching queries

### ISSUE THREAD

**Issue by hiscal2015** [pires/kubernetes-elasticsearch-cluster#83]
For data nodes using StatefulSet. e.g.
I have 3 PVs, pv0, pv1 and pv2, each have a volume with 50GB, then create data nodes with the volumeClaimTemplates requesting 50GB. 
The first time, 3 PVC has been created, named e.g. pvc0, pvc1 and pvc2, 
pvc0 was bound to pv0, 
pvc1 was bound to pv1, 
pvc2 was bound to pv2,
Then, I delete all of the resources created before, including PV and PVC, and create them again,
This time, 
pvc0 was bound to pv1, 
pvc1 was bound to pv0, 
pvc2 was bound to pv2,

Then my question is, any impact with this? Will data be lost? And will cluster info be changed? Thanks for the help!

**Comment by pires** [comment]
@wfhartford is this expected behavior?

**Comment by wfhartford** [comment]
I'm really not sure. I only have experience with the google container engine, where the PVs and PVCs are automatically created. The behaviour described does sound reasonable though. When the volume claims are created, they get associated with any available volume matching the criteria of the claim.

Typically, you should not be deleting all these resources and recreating them. Even if you need to delete your stateful set, you should leave the PVs and PVCs in place so that the correct volume can be associated with the appropriate pod in the stateful set.

**Comment by pires** [comment]
Should I close this?
