### ISSUE TITLE
Can you provide more details on how to override configuration

### ISSUE THREAD

**Issue by y2kbowen** [pires/kubernetes-elasticsearch-cluster#91]
Can  you provide details on how to override configuration?  At the bottom of the readme it says the config can be changed by setting the environment variable  path.conf=/path/to/my/config/. 

Am I setting this in the kubernetes yaml like this:
`spec:
   containers:
     env:
       - name: path.conf
          value: /path/to/my/config'
`

And how to I map the value from the container to some file on the VM?

**Comment by zetaab** [comment]
you cannot map single value, you need map whole configuration file. How you can mount some file from the VM inside container: https://kubernetes.io/docs/concepts/storage/volumes/#hostpath

**Comment by pires** [comment]
Thank you @zetaab!

**Comment by gytisgreitai** [comment]
Sorry for bumping a closed issue, but does this `path.conf` work in Kubernetes via the `env` array? 
There is an old issue on kubernetes which states that you cannot use env variables with dots in them: https://github.com/kubernetes/kubernetes/issues/2707#issuecomment-310650995

And it does seem so when I try with e.g. `path.repo`variable :

```
The Deployment "es-master" is invalid: spec.template.spec.containers[0].env[9].name: 
Invalid  value: "path.repo": a valid C identifier must start with alphabetic character 
or '_', followed by a string of alphanumeric characters or '_' (e.g. 'my_name', 
 or 'MY_NAME',  or 'MyName', regex used for validation is '[A-Za-z_][A-Za-z0-9_]*')
```

So what people are doing is passing those params with -E straight into elasticsearch:

```
    command: ["bin/elasticsearch"]
    args: ["-Ehttp.host=0.0.0.0", "-Etransport.host=127.0.0.1"]
```

If I understand correctly, this is not an option for an image that is used in this repo, since' it usess a wrapper `run.sh`script. So the only option(?) would be to mount configmap as volume under `/elasticsearch/config``

Or am I missing something?
